package com.storage.jpa;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.storage.BaseEntity;
import com.storage.jpa.Enums.ConnectorType;
import com.storage.jpa.Enums.FileType;

@Entity
@Table(name = "connector")
public class JpaConnector extends BaseEntity {

	@Enumerated(EnumType.STRING)
	@Column(name = "id", nullable = false, unique = true)
	@Id
	private ConnectorType id; // Manually set the ID as it is not autogenerated

	@OneToMany(mappedBy = "connector", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
	private Set<JpaConnectorMetadata> metadata = new HashSet<>();

	@Column(name = "description")
	private String description;

	@Column(name = "file_type", nullable = false)
	private FileType fileType;

	public JpaConnector() {
		super();
	}

	public JpaConnector(ConnectorType id) {
		super();
		this.id = id;
	}

	public ConnectorType getId() {
		return id;
	}

	public void setId(ConnectorType id) {
		this.id = id;
	}

	public Set<JpaConnectorMetadata> getMetadata() {
		return metadata;
	}

	public void setMetadata(Set<JpaConnectorMetadata> metadata) {
		this.metadata = metadata;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public FileType getFileType() {
		return fileType;
	}

	public void setFileType(FileType fileType) {
		this.fileType = fileType;
	}

}
